### ISSUE TITLE
If a section has a background, then the Canvas Zone Width setting is not applied

### ISSUE THREAD

**Issue by lordneeko** [spsprinkles/page-hacks#2]
Section with background styles applied
![image](https://github.com/user-attachments/assets/a3e36bcf-f721-4e2a-ae61-02d979401b2e)

The first 4 options for "background styles" works fine
![image](https://github.com/user-attachments/assets/b595765c-4ce4-4f3d-bf43-aee30aecc483)

But any other styles, or a custom background image, breaks the feature
![image](https://github.com/user-attachments/assets/f07c7e05-da8b-4275-8ab1-4c44b2b7fcd8)

This is the only setting that appears to be affected by background styles.

**Comment by gudatta** [comment]
Seems that some of them add the following element as the first child:

```html
<div class="bgOverlay-156" data-automation-id="CanvasZone-BgOverlay" aria-hidden="true"></div>
```

I've updated the style to target the element w/ data-automation-id='CanvasZone-SectionContainer' instead of targeting the first child.
