### ISSUE TITLE
Widget/button needs to have 0 padding/margin by default

### ISSUE THREAD

**Issue by lordneeko** [spsprinkles/page-hacks#3]
The Page Hacks widget doesn't appear in "view" mode for the page, but it does affect spacing of whatever section it is in. In addition, because it doesn't have 0 size, if I put it in a section with nothing else in it, the section still shows up in reading mode

![image](https://github.com/user-attachments/assets/ba8b2ed1-7864-40dc-9077-74a516d92009)

The only way currently to remove this is to use the page hack margin and padding setting, but this affects the entire page.

**Comment by gudatta** [comment]
I've updated this to hide the webpart element if the page is in display mode.
